### ISSUE TITLE
fork mit upstream mergen

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-latex#1]
Die Entwicklung zu diesem Projekt wird weiterhin unter [`RvNovae/dhge-latex`](https://github.com/RvNovae/dhge-latex) und nicht hier durchgeführt. Der upstream wurde länger nicht mehr mit diesem Repo germergt (aktuelle 18 commits behind).

@RvNovae Da das weiterhin primär dein Projekt ist, nehme ich an, dass du es nicht an die Organisation übertragen willst? 

Ich bin aber trotzdem der Meinung, dass wir die Fork in der Organisation behalten sollten. Vielleicht sollten wir das mergen mit [einer Action](https://github.com/marketplace/actions/fork-sync-with-upstream) automatisieren?

**Comment by RvNovae** [comment]
Jo, so eine Action, die automatisch den upstream aktualisiert hatten @photovoltex und ich auch schon mal angedacht.
Ist mit der Zeit etwas in Vergessenheit geraten, werden wir mal wieder ins Visier nehmen :)

**Comment by RvNovae** [comment]
Scheint funktioniert zu haben.

**Comment by Steve2955** [comment]
Vielen Dank, das ging viel schneller als gedacht 😂

**Comment by RvNovae** [comment]
Ich dacht ich machs mal gleich, eh ichs wieder vergess haha
